blank_issues_enabled: false

contact_links:
  - name: Amateur Radio Discussion
    url: https://github.com/username/memoryicomscript/discussions
    about: Ask questions, share experiences, and discuss amateur radio topics
    
  - name: Memory Channels Processor
    url: https://oe3lrt.gitlab.io/memory-channels-processor/
    about: Issues with the underlying memory-channels-processor tool
    
  - name: POTA API Status
    url: https://api.pota.app/programs/locations
    about: Check if POTA API is accessible before reporting POTA-related issues