name: Data Issue
description: Report incorrect or missing data in CSV files
title: "[Data] "
labels: ["data-issue", "needs-verification"]

body:
  - type: markdown
    attributes:
      value: |
        Report issues with the generated data (incorrect coordinates, missing entries, etc.)

  - type: dropdown
    id: data-type
    attributes:
      label: Data Type
      description: Which dataset has the issue?
      options:
        - POTA Parks
        - SOTA Summits  
        - Austrian Repeaters
        - Slovak Repeaters
        - Singapore Repeaters
        - Japanese Repeaters
        - Vienna FM Radio
        - PMR Channels
    validations:
      required: true

  - type: input
    id: specific-entry
    attributes:
      label: Specific Entry
      description: Which park, summit, or repeater has the issue?
      placeholder: AT-0001, OE1XYZ, Mount Example, etc.
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of problem is this?
      options:
        - Incorrect coordinates
        - Missing entry
        - Wrong name/description
        - Incorrect frequency
        - Wrong group assignment
        - Duplicate entry
        - Other
    validations:
      required: true

  - type: textarea
    id: current-data
    attributes:
      label: Current (Incorrect) Data
      description: What data is currently in the CSV?
      placeholder: Copy the current CSV line or describe what you see
      render: csv

  - type: textarea
    id: correct-data
    attributes:
      label: Correct Data
      description: What should the data be?
      placeholder: Provide the correct information
    validations:
      required: true

  - type: input
    id: source
    attributes:
      label: Information Source
      description: Where did you get the correct information?
      placeholder: Official website, local knowledge, etc.
    validations:
      required: true

  - type: textarea
    id: verification
    attributes:
      label: Verification
      description: How can we verify this information?
      placeholder: Links to official sources, coordinates verification, etc.

  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      description: How urgent is this correction?
      options:
        - Low - Minor improvement
        - Medium - Affects usability
        - High - Prevents operation
        - Critical - Safety issue
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other relevant details
      placeholder: Screenshots, links, related issues, etc.