name: Update README Stats

on:
  schedule:
    # Run daily at 07:00 UTC (after CSV generation)
    - cron: '0 7 * * *'
  workflow_dispatch:
  workflow_run:
    workflows: ["Generate Codeplug CSVs"]
    types: [completed]

jobs:
  update-stats:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Count generated files and update README
      run: |
        # Count CSV files
        TOTAL_CSV=$(find output -name "*.csv" -type f 2>/dev/null | wc -l || echo "0")
        POTA_FILES=$(find output -name "*pota*.csv" -type f 2>/dev/null | wc -l || echo "0") 
        SOTA_FILES=$(find output -name "*sota*.csv" -type f 2>/dev/null | wc -l || echo "0")
        
        # Get last commit date for generated files
        LAST_UPDATE=$(git log -1 --format="%ci" --grep="Auto-update CSV files" || echo "$(date -u '+%Y-%m-%d %H:%M:%S UTC')")
        LAST_UPDATE_SHORT=$(echo "$LAST_UPDATE" | cut -d' ' -f1)
        
        echo "Statistics:"
        echo "- Total CSV files: $TOTAL_CSV"
        echo "- POTA files: $POTA_FILES"
        echo "- SOTA files: $SOTA_FILES"
        echo "- Last update: $LAST_UPDATE_SHORT"
        
        # Create updated README with stats
        sed -i.bak \
          -e "s|**Latest Data Update**: Generated automatically every Sunday at 06:00 UTC|**Latest Data Update**: $LAST_UPDATE_SHORT (Generated automatically every Sunday at 06:00 UTC)|g" \
          -e "s|- **684 Parks Total**: 373 Austria + 247 Slovakia + 64 Singapore|- **$(echo $((373+247+64))) Parks Total**: 373 Austria + 247 Slovakia + 64 Singapore (Updated: $LAST_UPDATE_SHORT)|g" \
          README.md
          
    - name: Check for README changes
      id: readme-changes
      run: |
        if [[ -n $(git diff README.md) ]]; then
          echo "changes=true" >> $GITHUB_OUTPUT
          echo "README updated with new statistics"
        else
          echo "changes=false" >> $GITHUB_OUTPUT
          echo "No README changes needed"
        fi
        
    - name: Commit README updates
      if: steps.readme-changes.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        git add README.md
        git commit -m "Update README with latest file statistics
        
        Updated: $(date -u '+%Y-%m-%d %H:%M UTC')
        Auto-generated by update-readme workflow"
        
        git push
        
    - name: Create repository stats comment (on releases)
      if: steps.readme-changes.outputs.changes == 'true'
      run: |
        echo "Repository statistics updated in README.md"
        echo "This helps users see the current data availability at a glance"